pipeline {
    agent any

    stages {
        stage('Clone and Clean Repo') {
            steps {
                sh 'git clone https://github.com/fanantenana1/Java_Devops'
                sh 'mvn clean -f Java_Devops/Fanantenana/pom.xml'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test -f Java_Devops/Fanantenana/pom.xml'
            }
        }

        stage('Deploy') {
            steps {
                sh 'mvn package -f Java_Devops/Fanantenana/pom.xml'
                sh 'mvn deploy -f Java_Devops/Fanantenana/pom.xml'
                sh 'mvn sonar:sonar -f Java_Devops/Fanantenana/pom.xml'
            }
        }
    }

    post {
        success {
            echo 'Pipeline ran successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for details.'
        }
        always {
            echo 'This will run always, regardless of success or failure.'
        }
    }
}
