pipeline {
    agent any

    stages {
        stage('Clone & Clean') {
            steps {
                echo 'Code déjà cloné par Jenkins via SCM'
                sh 'mvn clean -f Fanantenana/pom.xml'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test -f Fanantenana/pom.xml'
            }
        }

        stage('Deploy') {
            steps {
                sh 'mvn package -f Fanantenana/pom.xml'
                sh 'mvn deploy -f Fanantenana/pom.xml'
            }
        }
    }

    post {
        success {
            echo 'Pipeline ran successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
